#ifndef NPBNLP_SNPYLM_H
#define NPBNLP_SNPYLM_H

// Switching NPYLM (WO-006, phase 1: generative core + count ledger).
//
// Generative model (npbnlp-math SKILL.md section 4): a sentence is a sequence
// of template tokens v_1..v_M generated by a background word HPYP G^bg; each
// token is either a normal word or a class-k NE symbol NE_k. The base measure
// of G^bg is the mixture
//     G0(v) = (1-pi) G0^spell(v) + pi * sum_k rho_k * delta_{NE_k},
// so escaping to the base either draws a spelling from the letter model
// (G0^spell) or an NE symbol (weighted by the GEM weights rho). When v = NE_k
// the surface string x_j is emitted by a class-specific chunk PYP H_k.
//
// There is no separate tag-transition model: the NE_k symbols live in G^bg's
// n-gram vocabulary, so the template n-gram carries both context and switching.
//
// hpyp only offers a *chunk*-level custom base measure (set_cbase); there is no
// word-level hook, and a bespoke `lm` subclass cannot be used as a base because
// wrap::add_a dispatches on typeid over {hpyp,vpyp,hdp} only and hpyp::_lpb(word)
// hard-codes character iteration. G^bg is therefore realised as an hpyp over
// *chunk* template tokens with set_cbase = the G0 mixture; the cbase add/remove
// delegates carry the pi/rho/spell bookkeeping and only fire on a base escape
// (a new root table), which is exactly the theoretically correct counting site.

#include"nio.h"
#include"hpyp.h"
#include"vpyp.h"
#include"clattice.h"
#include"vtable.h"
#include<memory>
#include<mutex>
#include<unordered_map>
#include<vector>

namespace npbnlp {
	class snpylm {
		public:
			snpylm();
			snpylm(int n, int hn, int hl, int k);
			virtual ~snpylm();
			// n   = background template n-gram order (>=2 required by the model)
			// hn  = per-class NE surface chunk-PYP order (unigram over spans = 1)
			// hl  = per-class / spell letter VPYP order
			// k   = number of NE classes registered at construction
			virtual void set(int v, int k);   // v = character vocabulary size
			virtual void set_gamma(double g); // Beta(1,gamma) gate prior
			virtual void set_alpha(double a); // GEM concentration
			// single-word NE frequency gate (rarity cue, WO-006 step 2). A
			// length-1 span may be an NE (z>=1) only if its word type is rare in
			// the training corpus (freq <= _freq_cap); high-frequency words (the
			// rich-get-richer fuel: の/を/年 ...) are barred from single-word NE.
			// count_freq() tallies the corpus word types (call over every
			// sentence before set_freq_cap); set_freq_cap() fixes the cap.
			virtual void count_freq(nsentence& s);
			// cap semantics: >0 = explicit cap; 0 = gate disabled; -1 = auto (the
			// cap is derived from the collected _wfreq, see snpylm.cc). count_freq
			// must have been called for -1 to have data to work on.
			virtual void set_freq_cap(int cap);
			// annealing: NE emission exponent E_k -> E_k^tau. tau>1 damps the NE
			// surface likelihood (suppresses the H_k rich-get-richer pull) during
			// warm-up; tau=1 (default) is the stationary model. O (E_0=1) is
			// unaffected. NOTE the exponent is tau (>1 suppresses), not 1/tau: the
			// observed degeneracy is all-NE, so early sampling must weaken NE, the
			// opposite sign to the all-O remedy sketched in math 4.7(iii).
			virtual void set_temp(double tau);
			// hard constraint (default on): an NE span (z>=1) is admissible only if
			// its chunk type (chunktype2, already computed by clattice2) contains an
			// entity script (kanji / katakana / latin / digit). Enforced structurally
			// in the lattice allowed set, so hiragana-only / punctuation-only spans
			// can never be NE. O(1): a single ch.type lookup, no character rescan.
			virtual void set_type_admission(bool f);
			// single-word (len==1) NE emission: when off (default), E_k for a
			// length-1 span bypasses the chunk-PYP cache and pays the base measure
			// H_k^0 directly, removing the rich-get-richer boost that lets a few
			// frequent words dominate a class. set true to restore the cached
			// predictive. See _emit_lp for the (deliberate) generative deficiency.
			virtual void set_l1_cache(bool f);
			// generic NE-slot backoff (default on): P(NE_k|ctx) is interpolated with
			// a class-agnostic P(NE_generic|ctx)*rho_k, so template-frame statistics
			// ("<NE> 氏 が", "<NE> は") pool across classes instead of thinning out
			// per class. --no_generic_backoff / set false disables it.
			virtual void set_generic_backoff(bool f);
			// generic-backoff mixture weight (0 < w < 1, default 0.5): weight of the
			// class-specific P(sigma|ctx) against the pooled generic slot. Out of
			// range throws. Serialized so parse reproduces the trained weight.
			virtual void set_gen_w(double w);
			// diagnostic (Phase A): dump per-span background scores for sentence i to
			// stderr and return. Emits `spanscore <sent> <char_s>-<char_e> <surp>
			// <fgain>` per lattice candidate; char offsets match NPBNLP_LATTICE_COVER.
			virtual void span_score_dump(nio& f, int i);
			virtual int n() const;
			virtual int k() const;
			virtual void slice(double a, double b); // Beta(a,b) slice params
			virtual void init(nsentence& s);
			virtual void add(nsentence& s);
			virtual void remove(nsentence& s);
			// blocked Gibbs draw of a segmentation+tagging for sentence i.
			// sample(): draw from the posterior (conditioning the slice on cur);
			// parse(): the MAP path. cur = the current assignment (for the slice).
			virtual nsentence sample(nio& f, int i);
			virtual nsentence sample(nio& f, int i, nsentence *cur);
			virtual nsentence parse(nio& f, int i);
			virtual void estimate(int iter);
			virtual void poisson_correction(int n = 1000);
			virtual void save(const char *file);
			virtual void load(const char *file);
			virtual void stats() const; // NPBNLP_SNPYLM_STATS diagnostic dump
		protected:
			int _n;      // background n-gram order
			int _hn;     // NE surface chunk PYP order
			int _hl;     // letter VPYP order
			int _l;      // maximum NE span length (lattice candidate cap)
			int _k;      // number of NE classes
			int _v;      // character vocabulary size
			double _gamma;
			double _alpha;
			double _pi;  // current P(new token is an NE symbol)
			double _tau; // NE emission annealing exponent (1 = stationary)
			bool _type_admission; // gate NE spans by admissible chunk type
			bool _l1_cache;       // len==1 NE uses the chunk-PYP cache (default off)
			int _freq_cap;        // single-word NE frequency cap (0 = disabled)
			// corpus word-type frequencies (word id -> count), measured from the
			// training corpus itself (unsupervised). A static table (not a CRP
			// ledger): add/remove of a sentence never touches it, so it does not
			// participate in the count roundtrip invariant. Serialized so the
			// gate is reproduced identically at parse time.
			std::unordered_map<int, int> _wfreq;
			double _a;   // slice Beta parameter a
			double _b;   // slice Beta parameter b
			std::vector<int> _clength; // per-chunktype span cap for clattice2
			// background template LM over template tokens (chunk-keyed for the
			// set_cbase hook). base = G0 mixture via the cbase delegates below.
			std::shared_ptr<hpyp> _bg;
			// generic NE-slot n-gram: a parallel context count model keyed on the
			// generic-replacement stream gvid (NE positions collapse to _ne_generic,
			// WO-007). It is a TARGETED ledger, seated only where an NE participates:
			//   (a) at every NE position j -> add(_ne_generic) (the slot itself);
			//   (b) at a word position j whose n-1 history window contains an NE ->
			//       add(tvid[j]) (the exit frame "<NE> 氏 が");
			//   (c) at EOS when the trailing window contains an NE -> add(0).
			// Contexts use gvid (先行 NE も generic 化), so frame statistics pool
			// across classes. No base measure (uniform int base) -- it is a
			// context-conditioned count table, not a generative LM.
			std::shared_ptr<hpyp> _bg_gen;
			int _ne_generic;        // the generic NE symbol id (wid, serialized)
			bool _generic_backoff;  // interpolate P(NE_k|ctx) with the generic slot
			double _gen_w;          // generic-backoff mixture weight (serialized)
			// normal-word spelling model G0^spell: a fixed-order character model,
			// seated char-by-char (no word.m scratch, so it cannot desync with the
			// per-class NE character models that share the same word objects).
			std::shared_ptr<hpyp> _spell;
			// per-class NE surface models H_k: a chunk PYP over whole NE spans whose
			// base H_k^0 is a per-class fixed-order character model (_hkletter). The
			// char base is wired through set_cbase (like G^bg's G0) rather than hpyp's
			// word-oriented _base: hpyp::_lpb(chunk) feeds whole *words* to its base,
			// which would score each span word atomically (flat, char-independent) and
			// also collide on the shared word.m letter-order scratch used by _spell.
			// The cbase model iterates the span's characters directly (no word.m).
			std::shared_ptr<std::vector<std::shared_ptr<hpyp> > > _hk;
			std::shared_ptr<std::vector<std::shared_ptr<hpyp> > > _hkletter;
			// class k <-> NE symbol word id, registered in the global wid dict.
			std::vector<int> _nek;          // k -> NE symbol id (index 0 unused)
			std::unordered_map<int, int> _id2k; // NE symbol id -> class k
			// base-escape counters (drive the pi/rho posteriors). Every increment
			// happens inside the cbase add delegate, every decrement inside the
			// cbase remove delegate, so they are add/remove symmetric by
			// construction.
			int _pine;  // NE tokens seated at the base
			int _piw;   // normal words seated at the base
			int _pieos; // reserved tokens (BOS/EOS/unk) seated at the base
			std::vector<int> _rho;         // per-class base-escape counts (GEM)
			// psi: per-class character-type multinomial over NE surfaces. _psi is a
			// flat (_k+1) x chartype::n count table (index _psii); an asymmetric
			// Dirichlet prior injects the language prior (kanji/katakana/alnum high,
			// hiragana/punct low) so classes prefer entity-like scripts unsupervised.
			std::vector<int> _psi;
			std::vector<double> _lambda;   // per-class NE length parameter
			std::vector<int> _necnt;       // per-class NE span count (for lambda)
			std::vector<double> _nelen;    // per-class total NE char length
			std::mutex _mutex;
			// G0 mixture: dispatched by token id (NE symbol / normal / reserved).
			double _g0_lp(chunk& tv);        // log G0(v)
			void _g0_add(chunk& tv);         // base escape: seat spelling / count
			void _g0_remove(chunk& tv);      // symmetric un-seating
			double _spell_lp(word& w);       // log G0^spell(w) via the char model
			void _spell_seat(word& w, bool add); // seat/un-seat a word's characters
			// H_k^0: per-class character surface base measure over an NE span.
			double _hk_surf_lp(int k, chunk& ch);   // log H_k^0(x) + Po(|x|) + log psi
			void _hk_surf_add(int k, chunk& ch);     // seat the span chars + psi counts
			void _hk_surf_remove(int k, chunk& ch);  // symmetric un-seating
			int _psii(int k, int t) const;           // flat index into _psi
			double _psi_lp(int k, chunk& ch);        // log psi(x|k) (char-type factor)
			int _kind(int id) const;         // >0 NE class, 0 normal, -1 reserved
			// true iff `id` is a registered class NE symbol (_nek[k], k>=1). O(1)
			// via the _id2k hash; the generic symbol _ne_generic is NOT a class
			// symbol and returns false. Used to fold NE symbols to _ne_generic in
			// the generic-slot context trie (gsig) and to detect NE in a history
			// window (ctx_has_ne) during the FFBS recursion.
			bool _is_ne_sym(int id) const;
			// single-word NE frequency gate: true iff a length-1 span headed by
			// word id `wid` may carry an NE class. Reserved / unseen ids (id<=1)
			// have freq 0 and are always admissible.
			bool _freq_ok(int wid) const;
			int _tvid(chunk& ch);            // template token id of a chunk
			void _install_cbase();
			void _resize(int k);             // grow class LMs / counters to k
			void _seat(nsentence& s, bool add);
			void _register_symbols();
			// inference helpers (semi-Markov FFBS over the template n-gram).
			int _sigma(chunk& ch, int k);            // template token id of (ch,k)
			double _emit_lp(int k, chunk& ch);       // E_k: 0 (O) / P(x|H_k)+Po(len)
			double _bg_lp(chunk& ch, int k, const context *c); // raw P(sigma|c) on _bg
			double _rho_k(int k) const;              // GEM predictive rho_k
			// transition score log P(sigma(ch,k)|ctx): _bg for O/EOS, and for NE the
			// generic-backoff interpolation using the parallel _bg_gen context cg.
			double _trans_lp(chunk& ch, int k, const context *c, const context *cg,
					bool ctx_has_ne);
			void _slice(clattice2& l, nsentence *cur);
			void _forward(clattice2& l, int i, const context *c, const context *cg,
					chunk& ch, int k, double emit, chunk& prev, int q, bool bos,
					vt& a, vt& b, int n, bool ctx_has_ne);
			void _backward(clattice2& l, int i, const context *c, const context *cg,
					chunk& ch, int k, chunk& prev, int q, bool bos, double& lpr,
					vt& b, int n, bool ctx_has_ne);
			nsentence _infer(nio& f, int i, nsentence *cur, bool best);
		private:
	};
}

#endif
