#ifndef NPBNLP_SNPYLM_H
#define NPBNLP_SNPYLM_H

// Switching NPYLM (WO-006, phase 1: generative core + count ledger).
//
// Generative model (npbnlp-math SKILL.md section 4): a sentence is a sequence
// of template tokens v_1..v_M generated by a background word HPYP G^bg; each
// token is either a normal word or a class-k NE symbol NE_k. The base measure
// of G^bg is the mixture
//     G0(v) = (1-pi) G0^spell(v) + pi * sum_k rho_k * delta_{NE_k},
// so escaping to the base either draws a spelling from the letter model
// (G0^spell) or an NE symbol (weighted by the GEM weights rho). When v = NE_k
// the surface string x_j is emitted by a class-specific chunk PYP H_k.
//
// There is no separate tag-transition model: the NE_k symbols live in G^bg's
// n-gram vocabulary, so the template n-gram carries both context and switching.
//
// hpyp only offers a *chunk*-level custom base measure (set_cbase); there is no
// word-level hook, and a bespoke `lm` subclass cannot be used as a base because
// wrap::add_a dispatches on typeid over {hpyp,vpyp,hdp} only and hpyp::_lpb(word)
// hard-codes character iteration. G^bg is therefore realised as an hpyp over
// *chunk* template tokens with set_cbase = the G0 mixture; the cbase add/remove
// delegates carry the pi/rho/spell bookkeeping and only fire on a base escape
// (a new root table), which is exactly the theoretically correct counting site.

#include"nio.h"
#include"hpyp.h"
#include"vpyp.h"
#include<memory>
#include<mutex>
#include<unordered_map>
#include<vector>

namespace npbnlp {
	class snpylm {
		public:
			snpylm();
			snpylm(int n, int hn, int hl, int k);
			virtual ~snpylm();
			// n   = background template n-gram order (>=2 required by the model)
			// hn  = per-class NE surface chunk-PYP order (unigram over spans = 1)
			// hl  = per-class / spell letter VPYP order
			// k   = number of NE classes registered at construction
			virtual void set(int v, int k);   // v = character vocabulary size
			virtual void set_gamma(double g); // Beta(1,gamma) gate prior
			virtual void set_alpha(double a); // GEM concentration
			virtual int n() const;
			virtual int k() const;
			virtual void init(nsentence& s);
			virtual void add(nsentence& s);
			virtual void remove(nsentence& s);
			virtual void estimate(int iter);
			virtual void poisson_correction(int n = 1000);
			virtual void save(const char *file);
			virtual void load(const char *file);
			virtual void stats() const; // NPBNLP_SNPYLM_STATS diagnostic dump
		protected:
			int _n;      // background n-gram order
			int _hn;     // NE surface chunk PYP order
			int _hl;     // letter VPYP order
			int _k;      // number of NE classes
			int _v;      // character vocabulary size
			double _gamma;
			double _alpha;
			double _pi;  // current P(new token is an NE symbol)
			// background template LM over template tokens (chunk-keyed for the
			// set_cbase hook). base = G0 mixture via the cbase delegates below.
			std::shared_ptr<hpyp> _bg;
			// normal-word spelling model G0^spell (letter infinity-gram).
			std::shared_ptr<vpyp> _spell;
			// per-class NE surface models H_k (index 0 unused) and their bases.
			std::shared_ptr<std::vector<std::shared_ptr<hpyp> > > _hk;
			std::shared_ptr<std::vector<std::shared_ptr<vpyp> > > _hkletter;
			// class k <-> NE symbol word id, registered in the global wid dict.
			std::vector<int> _nek;          // k -> NE symbol id (index 0 unused)
			std::unordered_map<int, int> _id2k; // NE symbol id -> class k
			// base-escape counters (drive the pi/rho posteriors). Every increment
			// happens inside the cbase add delegate, every decrement inside the
			// cbase remove delegate, so they are add/remove symmetric by
			// construction.
			int _pine;  // NE tokens seated at the base
			int _piw;   // normal words seated at the base
			int _pieos; // reserved tokens (BOS/EOS/unk) seated at the base
			std::vector<int> _rho;         // per-class base-escape counts (GEM)
			std::vector<double> _lambda;   // per-class NE length parameter
			std::vector<int> _necnt;       // per-class NE span count (for lambda)
			std::vector<double> _nelen;    // per-class total NE char length
			std::mutex _mutex;
			// G0 mixture: dispatched by token id (NE symbol / normal / reserved).
			double _g0_lp(chunk& tv);        // log G0(v)
			void _g0_add(chunk& tv);         // base escape: seat spelling / count
			void _g0_remove(chunk& tv);      // symmetric un-seating
			double _spell_lp(word& w);       // log G0^spell(w) via the letter VPYP
			int _kind(int id) const;         // >0 NE class, 0 normal, -1 reserved
			int _tvid(chunk& ch);            // template token id of a chunk
			void _install_cbase();
			void _resize(int k);             // grow class LMs / counters to k
			void _seat(nsentence& s, bool add);
			void _register_symbols();
		private:
	};
}

#endif
