cmake_minimum_required(VERSION 3.20.0)

set(CMAKE_VERBOSE_MAKEFILE true)
set(CMAKE_CXX_FLAGS_DEBUG_INIT "-Wall")
set(CMAKE_CXX_FLAGS_RELEASE_INIT "-O3 -Wall")
set(VERSION ${CMAKE_VERSION})
project(npbnlp CXX)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_EXPORT_COMPILE_COMMANDS ON)
if (NOT CMAKE_BUILD_TYPE)
	set(CMAKE_BUILD_TYPE Release)
endif()

add_subdirectory(io)
add_subdirectory(rd)
add_subdirectory(lm)
add_subdirectory(ma)
add_subdirectory(tg)
add_subdirectory(pa)
add_subdirectory(sb)
add_subdirectory(re)

option(BUILD_PYTHON "build python bindings" OFF)
if (BUILD_PYTHON)
	add_subdirectory(py)
endif()

enable_testing()
add_subdirectory(tests)
